In [2]:
import numpy as np
arr=np.array([10,20,30,40])
arr

array([10, 20, 30, 40])

In [3]:
arr + 5

array([15, 25, 35, 45])

In [4]:
arr * 2

array([20, 40, 60, 80])

In [5]:
arr -10

array([ 0, 10, 20, 30])

In [6]:
arr/2

array([ 5., 10., 15., 20.])

In [7]:
arr.shape

(4,)

In [8]:
arr.dtype

dtype('int32')

In [9]:
marks=np.array([88,45,79,95,67])
marks


array([88, 45, 79, 95, 67])

In [10]:
marks > 50

array([ True, False,  True,  True,  True])